### ISSUE TITLE
Fix authentication error on the plan GitHub Action

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/devops-security#23]
### Overview
We need to fix an error that is keeping Terraform Plan from running, so that ????

#### Details 
There is an error when the action is run. Run aws-actions/configure-aws-credentials@v4 

Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers

### Action Items

- [ ] Explore source of error and push code changes to fix. It may be the version of the action

### Resources/Instructions

https://github.com/hackforla/devops-security/actions/runs/8345911119/job/22911603189

**Comment by chelseybeck** [comment]
It's at version 4, so version isn't the issue https://github.com/aws-actions/configure-aws-credentials

**Comment by freaky4wrld** [comment]
@chelseybeck I was just taking a look over the issue.... 
<img width="1440" alt="image" src="https://github.com/hackforla/devops-security/assets/134206855/6e0a115c-a636-46a0-a5e6-f46452c41770">
if we are using `devops-security-gha` then don't you think that in the `terraform-plan.yaml` file the `was-region` should be

```yaml
        aws-region: us-east-1
```
instead of `us-west-1`

Also I was trying to test on my local repo, just want to ask for where I can find these tokens on aws
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`

Do I have to add those two in my local repo secrets, along with the `GITHUB_TOKEN`

**Comment by chelseybeck** [comment]
@freaky4wrld apologies for the late response. our aws region should be us-west-2 for everything

**Comment by chelseybeck** [comment]
Closing this as we found that the issue was w/ branch protections. Thanks @freaky4wrld
